openapi: 3.1.0
info:
  title: Dandelion Biographer Bot API
  description: >
    This API is for receiving webhooks from [Dandelion's public Biographer Bot
    instance](https://chat.openai.com/g/g-QGzfgKj6I-mylife-biographer-bot).
    ## Updates
    - updated functions after failure to connect
    - added: keywords, phaseOfLife, relationships to bot package
  version: 1.0.2
servers:
  - url: https://mylife.ngrok.app/api/v1
    description: Local development endpoint using ngrok for testing the Dandelion Biographer Bot GPT.
  - url: https://humanremembranceproject.org/api/v1
    description: Endpoint for receiving stories from the Dandelion Biographer Bot instance.
security:
  - bearerAuth: []
paths:
  /keyValidation/{mid}:
    post:
      x-openai-isConsequential: false
      operationId: DandelionKeyValidation
      summary: Dandelion Biographer Bot will access this endpoint to validate a `memberKey` in Dandelion.
      description: Endpoint for handling incoming registration webhook data from the Dandelion GPT service.
      parameters:
        - name: mid
          in: path
          required: true
          description: The `memberKey` data to be sent by Dandelion Biographer Bot. Visitor enters memberKey and it is kept in GPT memory and sent with each request so that Dandelion knows partition.
          example: memberHandle|ae3a090d-1089-4110-8575-eecd119f9d8e
          schema:
            maxLength: 256
            minLength: 40
            type: string
      responses:
        "200":
          description: A successful response indicating the member key is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Valid member.
                  data:
                    type: object
                    properties:
                      mbr_id:
                        maxLength: 256
                        minLength: 40
                        type: string
                      updates:
                        type: string
                      interests:
                        type: string
                      birthDate:
                        type: string
                        format: date-time
                      birthPlace:
                        type: string
                      fullName:
                        type: string
                      preferredName:
                        type: string
        "400":
          description: Invalid member. Field `memberKey` is not valid, check again with member.
  /memory/{mid}:
    post:
      x-openai-isConsequential: false
      operationId: DandelionSaveMemory
      summary: Dandelion Biographer Bot will access this endpoint to generate a `bio-story` document in Dandelion Cosmos.
      description: Endpoint for handling incoming registration webhook data from the Dandelion GPT service.
      parameters:
        - name: mid
          in: path
          required: true
          description: The `memberKey` data to be sent by Dandelion Biographer Bot. Visitor enters memberKey and it is kept in GPT memory and sent with each request so that Dandelion knows partition. Is **not** just a guid/uuid.
          example: memberHandle|ae3a090d-1089-4110-8575-eecd119f9d8e
          schema:
            maxLength: 256
            minLength: 40
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: The `memory` data sent by Dandelion Biographer Bot.
              type: object
              required:
                - keywords
                - summary
                - title
              properties:
                keywords:
                  description: Dandelion Biographer Bot interprets (or asks) keywords for this `memory`. Should not include relations or names, but would tag content dynamically. Each should be a single word or short phrase.
                  items:
                    description: A single word or short phrase to tag `memory` content.
                    maxLength: 64
                    type: string
                  maxItems: 12
                  minItems: 3
                  type: array
                mbr_id:
                  description: The `memberKey` given by member visitor. Is **not** just a guid/uuid.
                  exampple: memberHandle|ae3a090d-1089-4110-8575-eecd119f9d8e
                  maxLength: 256
                  minLength: 40
                  type: string
                phaseOfLife:
                  description: Dandelion Biographer Bot interprets (or asks) phase of life for this `memory`.
                  enum:
                    - birth
                    - childhood
                    - adolescence
                    - teenage
                    - young-adult
                    - adulthood
                    - middle-age
                    - senior
                    - end-of-life
                    - past-life
                    - other
                  type: string
                relationships:
                  description: Dandelion Biographer Bot does its best to record individuals (or pets) mentioned in this `memory`.
                  items:
                    description: A name of relational individual/pet to the `memory` content.
                    type: string
                  maxItems: 24
                  type: array
                summary:
                  description: Dandelion Biographer Bot summary of identified `memory`.
                  maxLength: 20480
                  type: string
                title:
                  description: Dandelion Biographer Bot determines title for this `memory`.
                  maxLength: 256
                  type: string
      responses:
        "200":
          description: Story submitted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  message:
                    type: string
                    example: Story submitted successfully.
                  success:
                    type: boolean
                    const: true
                    example: true
        "401":
          description: No story summary provided. Use `summary` field.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    const: false
                    example: false
                  message:
                    type: string
                    example: No story summary provided. Use `summary` field.
